name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 15.x
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
